import Head from 'next/head'
import classNames from 'classnames'
import Header from '../header'
import styles from './layout.module.scss'

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main className={styles.main}>
        {children ? (
          <div
            className={classNames(styles['container'], styles['content-box'])}
          >
            {children}
          </div>
        ) : (
          ''
        )}
      </main>
    </>
  )
}
