import Head from 'next/head'
import Header from '../header'
import styles from './layout.module.scss'
import Breadcrumbs from '../breadcrumbs'

export default function Layout({ children, breadcrumbs }) {
  return (
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main className={styles.main}>
        {children ? (
          <div className={styles.container}>
            {breadcrumbs ? <Breadcrumbs breadcrumbs={breadcrumbs} /> : ''}
            <div className={styles['content-box']}>{children}</div>
          </div>
        ) : (
          ''
        )}
      </main>
    </>
  )
}
