import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/header'
import Layout from '../components/layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* TODO: move to layout. */}
      <Header />
      <Layout>
        <Link href="/items">Click Me</Link>
      </Layout>
    </>
  )
}
